require_relative './config/environment'  #THE environent file for the variables is run first
require 'sinatra/activerecord/rake'  #just note there are many rake tasks here that are imported into this rake file fromthe sinatra gem that has rake tasks for Active record

desc "Runs a Pry console"
task :console do   #note that this rake task is not namespaced unlike the rest that will come from sinatra gem
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)  #because of this line we are going to be ab;e to see what is happening behind he Active record ORM
  
  # Open a Pry session
  Pry.start
end
