development:
  adapter: sqlite3 #remember that active record can support any ther adapter for db such as MySQL
  database: db/development.sqlite3  #when db in environment is specified to dev't,a migration will create a new db called development

test:
  adapter: sqlite3
  database: db/test.sqlite3 
